version: '3.4'
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: host
    environment:
      - PUID=1026 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - ${HOME}/media/downloads/ongoing:/downloads # download folder
      - ${HOME}/.config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1026 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/media/downloads/ongoing/torrent-blackhole:/downloads # place where to put .torrent files
      - ${HOME}/.config/jackett:/config # config files

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1026 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - ${HOME}/media/downloads/ongoing:/downloads # download folder
      - ${HOME}/.config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1026 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.config/sonarr:/config # config files
      - ${HOME}/media/downloads/series:/tv # tv shows folder
      - ${HOME}/media/downloads/ongoing:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1026 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=America/New_York # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.config/radarr:/config # config files
      - ${HOME}/media/downloads/movies:/movies # movies folder
      - ${HOME}/media/downloads/ongoing:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York # timezone
    network_mode: host
    volumes:
      - ${HOME}/.plex/db:/config # plex database
      - ${HOME}/.plex/transcode:/transcode # temp transcoded files
      - ${HOME}/media/downloads:/data # media library
